#sensors:
#  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    point_cloud_topic: /camera/depth_registered/points
#    max_range: 2.0
#    point_subsample: 2
#    padding_scale: 1.0
#    padding_offset: 0.1
#    filtered_cloud_topic: filtered_cloud

sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/image_raw
#    image_topic: /naoqi_driver_node/camera/depth/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.5
    far_clipping_plane_distance: 1.5
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.03
    filtered_cloud_topic: filtered_cloud
